// src/pages/Landing/Landing.jsx

import "./Landing.css";
import { Link } from "react-router-dom";
import hero from "../../assets/hero.png";

import {
  FaRobot,
  FaFileAlt,
  FaChartLine,
  FaHistory,
  FaUserGraduate,
  FaBrain,
  FaCheckCircle,
  FaStar,
  FaArrowRight,
  FaPlayCircle,
  FaQuoteLeft,
  FaGithub,
  FaLinkedin,
  FaTwitter,
  FaEnvelope,
} from "react-icons/fa";

import {
  HiOutlineDocumentReport,
  HiOutlineSparkles,
} from "react-icons/hi";

const features = [
  {
    icon: <FaFileAlt />,
    title: "AI Resume Analyzer",
    desc: "Upload your resume and receive ATS score, missing skills, strengths and AI suggestions.",
  },
  {
    icon: <FaRobot />,
    title: "Mock Interviews",
    desc: "Practice real interview questions generated by AI based on your target role.",
  },
  {
    icon: <FaBrain />,
    title: "Question Generator",
    desc: "Generate unlimited technical, HR and behavioral interview questions.",
  },
  {
    icon: <HiOutlineDocumentReport />,
    title: "AI Feedback",
    desc: "Get score, detailed explanation and correct answers after every response.",
  },
  {
    icon: <FaChartLine />,
    title: "Performance Dashboard",
    desc: "Track interview scores, resume improvements and overall preparation.",
  },
  {
    icon: <FaHistory />,
    title: "History",
    desc: "Access previous resume reports, interview attempts and AI feedback anytime.",
  },
];

const steps = [
  "Create Free Account",
  "Upload Resume",
  "Generate Questions",
  "Practice Mock Interview",
  "Receive AI Feedback",
  "Track Progress",
];

const whyChoose = [
  "AI Powered Interview Questions",
  "ATS Resume Score",
  "Detailed AI Feedback",
  "Real Interview Experience",
  "Progress Tracking",
  "Secure User Account",
];

const stats = [
  {
    number: "10K+",
    title: "Students",
  },
  {
    number: "95%",
    title: "Success Rate",
  },
  {
    number: "500+",
    title: "Companies",
  },
  {
    number: "24/7",
    title: "AI Assistant",
  },
];

const testimonials = [
  {
    name: "Rahul Sharma",
    company: "TCS",
    review:
      "PrepAI helped me crack my TCS interview. The AI feedback was incredibly useful.",
  },
  {
    name: "Sneha Patel",
    company: "Infosys",
    review:
      "The Resume Analyzer increased my ATS score from 63 to 91 within two days.",
  },
  {
    name: "Aman Gupta",
    company: "Accenture",
    review:
      "The mock interviews felt realistic and boosted my confidence before placement.",
  },
];

const faq = [
  {
    q: "How does AI evaluate my answers?",
    a: "PrepAI uses Groq AI to analyze correctness, communication, technical depth and confidence.",
  },
  {
    q: "Can I upload PDF resumes?",
    a: "Yes. Upload your PDF resume and receive a complete AI resume analysis.",
  },
  {
    q: "Is PrepAI free?",
    a: "Yes. Core features are free for learning and interview preparation.",
  },
  {
    q: "Can I practice unlimited interviews?",
    a: "Yes. Generate unlimited interview questions and practice anytime.",
  },
];

export default function Landing() {
  return (
    <div className="landing">
      {/* ================= NAVBAR ================= */}

      <header className="navbar">
        <div className="container nav-container">
          <Link className="logo" to="/">
  <HiOutlineSparkles />
  PrepAI
</Link>

          <nav>
            <a href="#home">Home</a>
            <a href="#features">Features</a>
            <a href="#how">How It Works</a>
            <a href="#about">About</a>
            <a href="#faq">FAQ</a>
          </nav>

          <div className="nav-buttons">
            <Link to="/login" className="login-btn">
              Login
            </Link>

            <Link to="/register" className="primary-btn">
              Get Started
            </Link>
          </div>
        </div>
      </header>

      {/* ================= HERO ================= */}

      <section className="hero container" id="home">
        <div className="hero-left">
          <span className="badge">
            🚀 AI Powered Interview Preparation Platform
          </span>

          <h1>
            Crack Your
            <span> Dream Job </span>
            With AI
          </h1>

          <p>
            Upload your resume, practice AI mock interviews, generate interview
            questions, receive intelligent feedback and track your performance —
            all in one platform.
          </p>

          <div className="hero-buttons">
            <Link to="/register" className="primary-btn hero-btn">
              Start Free
              <FaArrowRight />
            </Link>

           
          </div>

          <div className="hero-users">
            <div className="avatars">
              <span>A</span>
              <span>R</span>
              <span>S</span>
              <span>K</span>
            </div>

            <p>
              <strong>10,000+</strong> Students already preparing with PrepAI
             
            </p>
          </div>
        </div>

        <div className="hero-right">
          <img src={hero} alt="PrepAI Hero" />
        </div>
      </section>

      {/* ================= TRUSTED ================= */}

      <section className="trusted">
        <div className="container">
          <h3>Trusted By Students Preparing For</h3>

          <div className="companies">
            <span>Google</span>
            <span>Microsoft</span>
            <span>Amazon</span>
            <span>TCS</span>
            <span>Infosys</span>
            <span>Accenture</span>
          </div>
        </div>
      </section>

      {/* ================= FEATURES ================= */}

      <section className="features container" id="features">
        <div className="section-title">
          <span>Features</span>

          <h2>Everything You Need To Crack Interviews</h2>

          <p>
            One AI platform for resume analysis, interview practice and career
            preparation.
          </p>
        </div>

        <div className="feature-grid">
          {features.map((item, index) => (
            <div className="feature-card" key={index}>
              <div className="feature-icon">{item.icon}</div>

              <h3>{item.title}</h3>

              <p>{item.desc}</p>
            </div>
          ))}
        </div>
      </section>
            {/* ================= HOW IT WORKS ================= */}

      <section className="how-section" id="how">
        <div className="container">
          <div className="section-title">
            <span>How It Works</span>

            <h2>Start Your Interview Preparation In Minutes</h2>

            <p>
              Our AI guides you through every step—from resume analysis to
              interview feedback.
            </p>
          </div>

          <div className="steps-grid">
            {steps.map((step, index) => (
              <div className="step-card" key={index}>
                <div className="step-number">
                  {String(index + 1).padStart(2, "0")}
                </div>

                <h3>{step}</h3>

                <p>
                  Complete this step to move closer to your dream job with AI
                  assistance.
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ================= WHY CHOOSE ================= */}

      <section className="why-section" id="about">
        <div className="container why-container">
          <div className="why-left">
            <span className="small-title">
  Why Choose PrepAI
</span>

            <h2>
              Smarter Preparation.
              <br />
              Better Interviews.
            </h2>

            <p>
              PrepAI combines AI Resume Analysis, Mock Interviews,
              Intelligent Question Generation and Performance Tracking in one
              professional platform.
            </p>

            <div className="why-list">
              {whyChoose.map((item, index) => (
                <div className="why-item" key={index}>
                  <FaCheckCircle />

                  <span>{item}</span>
                </div>
              ))}
            </div>

            <Link to="/register" className="primary-btn">
              Start Preparing
            </Link>
          </div>

          <div className="why-right">
            <div className="dashboard-preview">
              <div className="dashboard-header">
                <span>Performance Dashboard</span>
              </div>

              <div className="dashboard-cards">
                <div className="mini-card">
                  <h3>85%</h3>
                  <p>Average Score</p>
                </div>

                <div className="mini-card">
                  <h3>12</h3>
                  <p>Mock Interviews</p>
                </div>

                <div className="mini-card">
                  <h3>18</h3>
                  <p>Questions Practiced</p>
                </div>

                <div className="mini-card">
                  <h3>91</h3>
                  <p>ATS Resume Score</p>
                </div>
              </div>

              <div className="graph-placeholder"></div>
            </div>
          </div>
        </div>
      </section>

      {/* ================= STATS ================= */}

      <section className="stats-section">
        <div className="container stats-grid">
          {stats.map((item, index) => (
            <div className="stat-card" key={index}>
              <h2>{item.number}</h2>

              <p>{item.title}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ================= TESTIMONIALS ================= */}

      <section className="testimonial-section">
        <div className="container">
          <div className="section-title">
            <span>Testimonials</span>

            <h2>Loved By Students</h2>

            <p>
              Thousands of students have improved their interview skills using PrepAI.
            </p>
          </div>

          <div className="testimonial-grid">
            {testimonials.map((item, index) => (
              <div className="testimonial-card" key={index}>
                <FaQuoteLeft className="quote-icon" />

                <div className="stars">
                  <FaStar />
                  <FaStar />
                  <FaStar />
                  <FaStar />
                  <FaStar />
                </div>

                <p>{item.review}</p>

                <div className="testimonial-user">
                  <div className="avatar">
                    {item.name.charAt(0)}
                  </div>

                  <div>
                    <h4>{item.name}</h4>
                    <span>{item.company}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ================= FAQ ================= */}

      <section className="faq-section" id="faq">
        <div className="container">
          <div className="section-title">
            <span>FAQ</span>

            <h2>Frequently Asked Questions</h2>
          </div>

          <div className="faq-list">
            {faq.map((item, index) => (
              <div className="faq-card" key={index}>
                <h3>{item.q}</h3>

                <p>{item.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
            {/* ================= CTA ================= */}

      <section className="cta-section">
        <div className="container cta-container">
          <span className="cta-badge">
            🚀 Start Your Interview Journey Today
          </span>

          <h2>
            Ready To Crack
            <br />
            Your Dream Job?
          </h2>

          <p>
            Join thousands of students improving their interview skills with AI.
            Practice smarter, receive instant feedback and land your dream job
            faster.
          </p>

          <div className="cta-buttons">
            <Link to="/register" className="primary-btn">
              Start Free
            </Link>

            <Link to="/login" className="secondary-btn">
              Login
            </Link>
          </div>
        </div>
      </section>

      {/* ================= FOOTER ================= */}

      <footer className="footer">
        <div className="container footer-grid">
          <div className="footer-about">
        <h2>PrepAI</h2>

            <p>
              AI-powered interview preparation platform helping students crack
              technical interviews with resume analysis, AI feedback and mock
              interviews.
            </p>

            <div className="footer-socials">
              <a href="/">
                <FaGithub />
              </a>

              <a href="/">
                <FaLinkedin />
              </a>

              <a href="/">
                <FaTwitter />
              </a>

              <a href="/">
                <FaEnvelope />
              </a>
            </div>
          </div>

          <div className="footer-links">
            <h3>Platform</h3>

            <Link to="/">Home</Link>

            <Link to="/register">Register</Link>

            <Link to="/login">Login</Link>

            <Link to="/dashboard">Dashboard</Link>
          </div>

          <div className="footer-links">
            <h3>Resources</h3>

            <a href="#features">Features</a>

            <a href="#how">How It Works</a>

            <a href="#faq">FAQ</a>

            <a href="/">Privacy Policy</a>
          </div>

          <div className="footer-links">
            <h3>Contact</h3>

            <p>Pune, Maharashtra</p>

            <p>support@prepai.com</p>

            <p>+91 98765 43210</p>
          </div>
        </div>

        <div className="footer-bottom">
          <p>
            © {new Date().getFullYear()} PrepAI. All Rights Reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}